### ISSUE TITLE
[BUG]- Select Field Label

### ISSUE THREAD

**Issue by tpszhao** [wtLau/brian-lau.ca_V2#113]
## Describe the bug 🐛
<img width="253" alt="Screen Shot 2022-06-02 at 10 53 03 PM" src="https://user-images.githubusercontent.com/54560658/171795474-4dd96a99-c3d2-4850-bf9c-32d3a1b5fafc.png">

### Issue:

- 

### Steps To Reproduce

1. 

### Expected behavior

- [ ] 

---

**Comment by tpszhao** [comment]
PR #114

**Comment by wtLau** [comment]
Thanks!! <3
